[build]
builder = "nixpacks"

[deploy]
startCommand = "echo 'Please set root directory to backend/ or frontend/'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# This file tells Railway this is a multi-service project
# You need to create separate services in Railway dashboard
# and set the root directory for each service 